name: CI/CD Pipeline for Node.js App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Change to the application directory
    - name: Set application directory context
      run: cd ./node

    # Step 3: Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    # Step 4: Install dependencies
    - name: Install dependencies
      run: |
        cd ./node
        npm install

    # Step 5: Run tests (if any)
    - name: Run tests
      run: |
        cd ./node
        npm test

    # Step 6: Build the Docker image
    - name: Build Docker image
      run: |
        cd ./node
        docker build -t node .

    # Step 7: Deploy to AWS Elastic Beanstalk
    - name: Deploy to Elastic Beanstalk
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1
      run: |
        cd ./node
        zip -r app.zip .
        aws elasticbeanstalk create-application-version \
          --application-name "node" \
          --version-label v1 \
          --source-bundle S3Bucket="elasticbeanstalk-apps-123"
        aws elasticbeanstalk update-environment \
          --environment-name "node-env" \
          --version-label v1
